build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base-debian:bullseye
  amd64: ghcr.io/home-assistant/amd64-base-debian:bullseye
  armhf: ghcr.io/home-assistant/armhf-base-debian:bullseye
  armv7: ghcr.io/home-assistant/armv7-base-debian:bullseye
  i386: ghcr.io/home-assistant/i386-base-debian:bullseye
codenotary:
  base_image: codenotary@home-assistant.io
  signer: kim.asplund@gmail.com
args:
  PG_MAJOR: 17
  PG_VERSION: 17.0
  POSTGIS_VERSION: 3.5.2 