name: "PostgreSQL 17 with PostGIS 3.5.2"
version: "0.1.0"
slug: "postgresql_postgis"
description: "PostgreSQL 17 database server with PostGIS 3.5.2 extension"
url: "https://github.com/kimasplund/homeassistant_postgis"
icon: "icon/icon.png"
arch:
  - aarch64
  - amd64
init: false
startup: services
boot: auto
services:
  - mqtt:need
ports:
  5432/tcp: 5432
map:
  - data:/var/lib/postgresql/data:rw
options:
  databases:
    - homeassistant
  logins:
    - username: homeassistant
      password: homeassistant
  rights:
    - database: homeassistant
      username: homeassistant
      privileges: ALL
  ssl: false
  backup_time: "01:30"
  max_connections: 50
  shared_buffers: "128MB"
  work_mem: "4MB"
  maintenance_work_mem: "64MB"
  effective_cache_size: "512MB"
  server_args: ""
  allow_from: []
schema:
  databases:
    - str
  logins:
    - username: str
      password: str
  rights:
    - database: str
      username: str
      privileges: str
  ssl: bool
  backup_time: match(^([0-1][0-9]|2[0-3]):([0-5][0-9])$)
  max_connections: int(1,1000)
  shared_buffers: str
  work_mem: str
  maintenance_work_mem: str
  effective_cache_size: str
  server_args: str?
  allow_from:
    - str?
image: "ghcr.io/kimasplund/{arch}-homeassistant-postgis" 