name: Build and publish

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build ${{ matrix.arch }} add-on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: ["aarch64", "amd64", "armhf", "armv7", "i386"]
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/${{ matrix.arch }}
          push: ${{ github.event_name != 'pull_request' }}
          build-args: |
            BUILD_FROM=${{ matrix.arch == 'aarch64' && 'ghcr.io/home-assistant/aarch64-base-debian:bullseye' 
                          || matrix.arch == 'amd64' && 'ghcr.io/home-assistant/amd64-base-debian:bullseye' 
                          || matrix.arch == 'armhf' && 'ghcr.io/home-assistant/armhf-base-debian:bullseye' 
                          || matrix.arch == 'armv7' && 'ghcr.io/home-assistant/armv7-base-debian:bullseye' 
                          || matrix.arch == 'i386' && 'ghcr.io/home-assistant/i386-base-debian:bullseye' }}
            BUILD_ARCH=${{ matrix.arch }}
            BUILD_VERSION=${{ github.ref_name }}
          tags: |
            ghcr.io/kimasplund/${{ matrix.arch }}-homeassistant-postgis:latest
            ${{ github.event_name != 'pull_request' && github.ref_name != 'main' && format('ghcr.io/kimasplund/{0}-homeassistant-postgis:{1}', matrix.arch, github.ref_name) || '' }}
          cache-from: type=gha
          cache-to: type=gha,mode=max 