name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set tag name
        id: tag
        run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
      
      - name: Extract version from tag
        id: version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Get Changelog Entry
        id: changelog
        run: |
          VERSION="${{ steps.version.outputs.VERSION }}"
          CHANGELOG=$(sed -n "/## $VERSION/,/## /p" CHANGELOG.md | sed '1d;$d')
          CHANGELOG="${CHANGELOG//'%'/'%25'}"
          CHANGELOG="${CHANGELOG//$'\n'/'%0A'}"
          CHANGELOG="${CHANGELOG//$'\r'/'%0D'}"
          echo "CHANGELOG<<EOF" >> $GITHUB_OUTPUT
          echo "$CHANGELOG" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ steps.version.outputs.VERSION }}
          body: |
            # PostgreSQL 17 with PostGIS 3.5.2 - v${{ steps.version.outputs.VERSION }}
            
            ## Changes in this release:
            ${{ steps.changelog.outputs.CHANGELOG || 'No changelog provided' }}
            
            ## Supported architectures:
            - amd64 (64-bit x86)
            - aarch64 (ARM 64-bit)
            
            ## Installation:
            Add the repository URL to your Home Assistant Add-on Store:
            ```
            https://github.com/kimasplund/homeassistant_postgis
            ```
          draft: false
          prerelease: ${{ contains(github.ref, 'alpha') || contains(github.ref, 'beta') || contains(github.ref, 'rc') }}
          token: ${{ secrets.GITHUB_TOKEN }} 